Repository sygmaprotocol/explorer-ui, pull requests merged in 2024-01, with the labels that each got.

#138 chore(main): release 1.1.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#142 feat: gnosis chiado and arbitrum sepolia
  .github/workflows/cf-deploy-test.yml
  public/assets/icons/arbitrum.svg
  src/utils/Helpers.tsx
Labels: QA

#140 fix: refactor dates logic
  src/utils/Helpers.test.ts
  src/utils/Helpers.tsx
Labels: Bug, QA

#145 chore(main): release 1.2.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending
